let name="Faheem";
console.log(name[0])
console.log(name[1])
console.log(name[2])
console.log(name[3])
console.log(name[4])
console.log(name[5])
console.log(name.toUpperCase())
console.log(name.length)
console.log(name.slice(1,4))
console.log(name.replace("ee", "i"))
console.log(name.concat(" ", "Nazir"))